// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIFY9esnsQ3Q7vqFL82iPLRGioJgT-Jyk',
    appId: '1:1020716110002:web:1a873efdc0f737281e79ab',
    messagingSenderId: '1020716110002',
    projectId: 'store-fd673',
    authDomain: 'store-fd673.firebaseapp.com',
    databaseURL: 'https://store-fd673-default-rtdb.firebaseio.com',
    storageBucket: 'store-fd673.appspot.com',
    measurementId: 'G-3NFJ6ME35Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXFOCfaY28-zPLEwBQLdUzUvIGnzH8uCI',
    appId: '1:1020716110002:android:ca3713c21d6d924d1e79ab',
    messagingSenderId: '1020716110002',
    projectId: 'store-fd673',
    databaseURL: 'https://store-fd673-default-rtdb.firebaseio.com',
    storageBucket: 'store-fd673.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAESCXNEcnAnZr2dusS0tAJDiMs-NzkNaU',
    appId: '1:1020716110002:ios:94876e5020dfee911e79ab',
    messagingSenderId: '1020716110002',
    projectId: 'store-fd673',
    databaseURL: 'https://store-fd673-default-rtdb.firebaseio.com',
    storageBucket: 'store-fd673.appspot.com',
    iosBundleId: 'com.sixamtech.dellevr',
  );
}
