// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxXem2CqAL-HucEey7v9DcxH2l3cVofic',
    appId: '1:591532309022:web:d9d606c5eb367491ce8c0f',
    messagingSenderId: '591532309022',
    projectId: 'nexus-graph',
    authDomain: 'nexus-graph.firebaseapp.com',
    databaseURL: 'https://nexus-graph-default-rtdb.firebaseio.com',
    storageBucket: 'nexus-graph.appspot.com',
    measurementId: 'G-546ZK50GVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaWW4s8czfvWWg4hYQ7NG2NvHmbglJrUM',
    appId: '1:591532309022:android:b5965bbf38865a9bce8c0f',
    messagingSenderId: '591532309022',
    projectId: 'nexus-graph',
    databaseURL: 'https://nexus-graph-default-rtdb.firebaseio.com',
    storageBucket: 'nexus-graph.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB193MCSDjoia3evbAp_YL7sc2_iDV86VM',
    appId: '1:591532309022:ios:dc068769bd688d52ce8c0f',
    messagingSenderId: '591532309022',
    projectId: 'nexus-graph',
    databaseURL: 'https://nexus-graph-default-rtdb.firebaseio.com',
    storageBucket: 'nexus-graph.appspot.com',
    iosBundleId: 'com.sixamtech.dellevr',
  );

}